### ISSUE TITLE
Shards executable is missing on Windows

### ISSUE THREAD

**Issue by naqvis** [oprypin/install-crystal#4]
Using the `v1.3.0` and performing a install on `windows-latest` is installing the Crystal, but no `shards` executable.

```yaml
jobs:
  build:
    timeout-minutes: 30
    strategy:
      fail-fast: false
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Crystal
      uses: oprypin/install-crystal@v1.3.0
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
```

```shell
Run oprypin/install-crystal@v1.3.0
Looking for latest Crystal build
Found Crystal release https://github.com/crystal-lang/crystal/actions/runs/814765503
Downloading Crystal source for 421fa11bf05b11441b74bbeb2762b673f96fec3f
Downloading Crystal build
Extracting Crystal source
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\0851894a-7039-4417-8ed2-de84da05df38', 'D:\a\_temp\aaa78362-e1f5-4afd-af11-a10070374271')"
Extracting Crystal build
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\645e2361-e87d-48de-8ca4-9fbbd7f39bc1', 'D:\a\_temp\aaa78362-e1f5-4afd-af11-a10070374271\crystal-lang-crystal-421fa11')"
Setting up environment for Crystal
cmd /c "set && echo --- && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" >nul && set"
crystal --version
Crystal 1.1.0-dev (2021-05-05)

LLVM: 10.0.0
Default target: x86_64-pc-windows-msvc
```

```

Run shards install
shards: D:\a\_temp\f3017ae0-7a1b-4a7a-b0d0-78cc0768de1f.ps1:2
Line |
   2 |  shards install
     |  ~~~~~~
     | The term 'shards' is not recognized as a name of a cmdlet, function, script file, or executable
     | program. Check the spelling of the name, or if a path was included, verify that the path is correct
     | and try again.

Error: Process completed with exit code 1.
```
